#!/bin/bash

echo "=== CRM Database Migration Helper ==="
echo ""
echo "Bu script kullanici_sorumluluk_bolgesi tablosuna eksik alanları ekler."
echo ""
echo "Migration file: fix_kullanici_sorumluluk_bolgesi.sql"
echo ""
echo "Çalıştırmadan önce:"
echo "1. Database bağlantı bilgilerinizi kontrol edin"
echo "2. Database backup'ınızın olduğundan emin olun"
echo ""
echo "Migration'ı çalıştırmak için:"
echo "mysql -u [username] -p [database_name] < database_migrations/fix_kullanici_sorumluluk_bolgesi.sql"
echo ""
echo "Örnek:"
echo "mysql -u root -p crm_database < database_migrations/fix_kullanici_sorumluluk_bolgesi.sql"
echo ""
echo "Migration şu alanları ekleyecek:"
echo "- baslangic_tarihi (DATE)"
echo "- bitis_tarihi (DATE)" 
echo "- ulke_id (VARCHAR(2), default: 'TR')"
echo "- aciklama (TEXT)"
echo "- Gerekli indeksler ve foreign key constraints"
echo ""
echo "=== TABLO YAPISINI KONTROL ETMEK İÇİN ==="
echo "DESCRIBE kullanici_sorumluluk_bolgesi;"
echo ""
